
----------------------------------script para actualizar los nit q no existen	en tabla third

USE [FSC_eProject]
UPDATE THIRD SET CODE='NIT_D1'  WHERE ID = 34
UPDATE THIRD SET CODE='NIT_D2'  WHERE ID = 35
UPDATE THIRD SET CODE='NIT_D3'  WHERE ID = 36
UPDATE THIRD SET CODE='NIT_D4'  WHERE ID = 37
UPDATE THIRD SET CODE='NIT_D5'  WHERE ID = 38
UPDATE THIRD SET CODE='NIT_D6'  WHERE ID = 39
UPDATE THIRD SET CODE='NIT_D7'  WHERE ID = 40
UPDATE THIRD SET CODE='NIT_D8'  WHERE ID = 41
UPDATE THIRD SET CODE='NIT_D9'  WHERE ID = 42
UPDATE THIRD SET CODE='NIT_D10'  WHERE ID = 43
UPDATE THIRD SET CODE='NIT_D11'  WHERE ID = 44
UPDATE THIRD SET CODE='NIT_D12'  WHERE ID = 45
UPDATE THIRD SET CODE='NIT_D13'  WHERE ID = 46
UPDATE THIRD SET CODE='NIT_D14'  WHERE ID = 47
UPDATE THIRD SET CODE='NIT_D15'  WHERE ID = 48
UPDATE THIRD SET CODE='NIT_D16'  WHERE ID = 49
UPDATE THIRD SET CODE='NIT_D17'  WHERE ID = 50
UPDATE THIRD SET CODE='NIT_D18'  WHERE ID = 51
UPDATE THIRD SET CODE='NIT_D19'  WHERE ID = 52
UPDATE THIRD SET CODE='NIT_D20'  WHERE ID = 53
UPDATE THIRD SET CODE='NIT_D21'  WHERE ID = 54
UPDATE THIRD SET CODE='NIT_D22'  WHERE ID = 55
UPDATE THIRD SET CODE='NIT_D23'  WHERE ID = 56
UPDATE THIRD SET CODE='NIT_D24'  WHERE ID = 57
UPDATE THIRD SET CODE='NIT_D25'  WHERE ID = 58
UPDATE THIRD SET CODE='NIT_D26'  WHERE ID = 59
