USE [FSC_eSecurity]
GO
print 'Actualizando Menus FSC'
/****** Object:  Table [dbo].[Menu]    Script Date: 09/16/2013 08:31:11 ******/
SET IDENTITY_INSERT [dbo].[Menu] ON

INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (189, N'administrador', N'', N'T', 99, 1)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (190, N'formulacion', N'', N'T', 99, 1)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (191, N'ejecucion', N'', N'T', 99, 1)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (192, N'herramientas', N'', N'T', 99, 1)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (193, N'esecurity', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (194, N'Panel General de Proyectos', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (195, N'Planeación General ', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (196, N'Admin Procesos BPM', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (197, N'Reportes', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (198, N'Idea', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (199, N'Proyecto', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (200, N'Contratación', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (201, N'Inicio Proyecto', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (202, N'Cronograma del Proyecto', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (203, N'Indicador', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (204, N'Acta de Seguimiento', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (205, N'Gestion del Riesgo', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (206, N'Ejecución Operadores', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (207, N'Cierre del Proyecto', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (208, N'Evaluación', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (209, N'Reportes', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (210, N'Encuesta', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (211, N'Documentos', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (212, N'Foro', N'', N'T', 99, 2)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (213, N'Empresa', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (214, N'Menus', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (215, N'Tipo Documento', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (216, N'Perspectiva', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (217, N'Objetivo Estrategico', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (218, N'Gerencia', N' ', N'T', 99, 3)
GO
print 'Processed 200 total records'
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (219, N'Estrategia', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (220, N'Linea estrategica o Linea de Acción', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (221, N'Programa', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (222, N'Componentes de programa', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (223, N'Actividad de la estrategia', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (224, N'Actor', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (225, N'Destinatario', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (226, N'Planeación General', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (227, N'Investigación y Desarrollo', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (228, N'Convocatorias', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (229, N'Nueva Empresa', N' /FSC/GeneralPlanning/addENTERPRISE.aspx?op=add', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (230, N'Buscar Empresa', N' /FSC/GeneralPlanning/searchENTERPRISE.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (231, N'Buscar Item', N' /FSC/Administrator/AdminMenu.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (233, N'Nuevo Destinatario', N' /FSC/Execution/addAddressee.aspx?op=add', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (234, N'Buscar Destinatario', N' /FSC/Execution/searchAddressee.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (236, N'Nueva Perspectiva', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (237, N'Buscar Perspectiva', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (243, N'Nuevo Objetivo Estrategico', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (244, N'Nuevo Gerencia', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (245, N'Nuevo Estrategia', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (246, N'Nueva Linea Estrategica', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (247, N'Nueva Programa', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (248, N'Buscar Objetivo Estrategico', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (249, N'Buscar Gerencia', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (250, N'Buscar Estrategia', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (251, N'Buscar Linea Estrategica', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (252, N'Buscar Programa', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (255, N'Nuevo Componente de Programa', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (256, N'Nuevo Actividad de la estrategia', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (257, N'Buscar Actividad de la estrategia', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (263, N'Nuevo Actor', N' /FSC/GeneralPlanning/addThird.aspx?op=add', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (264, N'Plan de Acción General', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (265, N'Inventario de Ideas', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (266, N'Estado de Convocatorias', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (267, N'Nuevo Tipo Documento', N' /FSC/Engagement/addDocumentType.aspx?op=add', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (268, N'Buscar Actor', N' /FSC/GeneralPlanning/searchThird.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (269, N'Detalle Estrategia', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (270, N'Mapa de Actores', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (271, N'Lista de Propuestas', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (272, N'Buscar Tipo Documento', N' /FSC/Engagement/searchDocumentType.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (273, N'Detalle Linea Estrategica', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (274, N'Inventario de Indicadores', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (275, N'Gantt de Actividades de Estrategia', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (276, N'Actor', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (281, N'Nueva Idea', N' /FSC/ResearchAndDevelopment/addIdea.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (282, N'Crear Proyecto', N' /FSC/FormulationAndAdoption/addProject.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (283, N'Generar Contrato', N' /FSC/Engagement/addContractRequest.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (284, N'Nuevo Registrar plan de ejecucion Contractual', N' /FSC/OperationalPlanning/addExecutionContractualPlanRegistry.aspx?op=add', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (285, N'Buscar Idea', N' /FSC/ResearchAndDevelopment/searchIdea.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (286, N'Buscar Proyecto', N' /FSC/FormulationAndAdoption/searchProject.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (287, N'Buscar Contrato', N' /FSC/Engagement/searchContractRequest.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (288, N'Buscar Registrar plan de ejecucion Contractual', N' /FSC/OperationalPlanning/addExecutionContractualPlanRegistry.aspx?op=add', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (289, N'Aprobar Idea', N' /FSC/FormulationAndAdoption/addProjectApprovalRecord.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (290, N'Aprobar Proyecto', N' /FSC/FormulationAndAdoption/addProjectApproval.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (291, N'Buscar aprobación de ideas', N' /FSC/FormulationAndAdoption/searchProjectApprovalRecord.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (292, N'Plan de ejecución Contractual', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (295, N'Actividad', N'', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (296, N'Subactividad', N'', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (297, N'Generar Acta de Inicio', N' /FSC/FomsProceedings/Proceeding_main.aspx?tp=str', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (298, N'Ingresar Cronograma', N' /FSC/FormulationAndAdoption/addproyectchargemasive.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (299, N'Nueva Actividad', N' /FSC/FormulationAndAdoption/addActivity.aspx?op=add', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (300, N'Nueva SubActividad', N' /FSC/FormulationAndAdoption/addSubActivity.aspx?op=add', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (301, N'Editar Cronograma', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (302, N'Buscar Actividad', N' /FSC/FormulationAndAdoption/searchActivity.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (303, N'Buscar SubActividad', N' /FSC/FormulationAndAdoption/searchSubActivity.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (313, N'Nuevo Indicador', N' /FSC/GeneralPlanning/addIndicator.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (314, N'Generar Acta de Seguimiento', N' /FSC/FomsProceedings/Proceeding_main.aspx?tp=trc', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (315, N'Nuevo Riesgo (Incluye toda la clasificación y la acción de mitigación)', N' /FSC/FormulationAndAdoption/addRisk.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (316, N'Registrar Testimonios y Aprendizajes', N' /FSC/Execution/addExecution.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (317, N'Generar Acta de Cierre', N' /FSC/FomsProceedings/Proceeding_main.aspx?tp=cls', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (318, N'Nuevo Registro de Acta de cierre', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (319, N'Registrar testimonios, ajustes y aprendizajes', N' /FSC/Execution/addExecution.aspx?op=add', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (320, N'Busqueda (incluye busqueda por toda la clasificacion)', N' /FSC/FormulationAndAdoption/searchRisk.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (321, N'Listado de subactividades pendientes', N' /FSC/Execution/subActivityMainPanelTODO-LIST.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (322, N'Lecciones Aprendidas', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (323, N'Buscar Registro de Acta de cierre', N' ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (324, N'Busqueda (incluye busqueda por toda la clasificacion)', N' /FSC/Execution/searchExecution.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (325, N'Buscar Indicador', N' /FSC/GeneralPlanning/searchIndicator.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (326, N'Listado de subactividades pendientes', N' /FSC/Execution/addSubActivityInformationRegistry.aspx?op=add&idsubactivity=2593', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (327, N'Listado de ajustes pendientes', N' /V9/BPM/InternalParticipant/TaskList.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (330, N'Evaluación Proveedor', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (331, N'Nueva Evaluacion Proveedor', N' /FSC/ResearchAndDevelopment/addSupplierEvaluation.aspx?op=add', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (332, N'Buscar Evaluacion Proveedor', N' /FSC/ResearchAndDevelopment/searchSupplierEvaluation.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (333, N'Reportes', N'', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (334, N'Formulacion y Planeación', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (335, N'Ejecución', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (336, N'Reportes de Contratación', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (339, N'Ejecución', N'', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (340, N'Estado de la solicitud de contratos', N' /FSC/Report/Engagement/reportContractsRequest.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (341, N'Datos basicos de Proyecto', N' /FSC/Report/FormulationAndAdoption/reportBasicProjectData.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (342, N'Lista de Subactividades', N' /FSC/Report/Execution/reportActivities.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (343, N'Listado general de contratos', N' /FSC/Report/Engagement/generalListContracts.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (344, N'Matriz de Indicadores', N' /FSC/Report/FormulationAndAdoption/reporMatrixIndicator.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (345, N'Banco de documentos', N' /FSC/Report/ResearchAndDevelopment/ReportDocuments.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (346, N'Plan de contratacion', N' /FSC/Report/OperationalPlanning/reportRecruitmentPlan.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (347, N'Plan de Ejecución', N' /FSC/Report/reportExecutionPlan.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (348, N'Productos de Proyecto', N' /FSC/Report/ResearchAndDevelopment/ReportProducts.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (349, N'Cronograma del proyecto', N' /FSC/Report/FormulationAndAdoption/reportProjectChronogram.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (350, N'Listado de buenas practicas', N' /FSC/Report/ResearchAndDevelopment/ReportGoodPractice.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (351, N'Matriz de Riesgos', N' /FSC/Report/FormulationAndAdoption/reportRiskMatrix.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (352, N'Actividades Vs Ejecución', N' /FSC/Report/FormulationAndAdoption/ReportSubactivitiesVsExecution.aspx', N'T', 99, 4)
GO
print 'Processed 300 total records'
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (353, N'Plan de contratación', N' /FSC/Report/OperationalPlanning/reportRecruitmentPlan.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (354, N'Estadisticas', N' /FSC/Report/ResearchAndDevelopment/ReportStatistics.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (355, N'Aprendizaje, Logros y Ajustes', N' /FSC/Report/FormulationAndAdoption/reportlearning.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (356, N'Lista de testimonios', N' /FSC/Report/FormulationAndAdoption/ReporTestimonyList.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (357, N'Grafica de Encuestas', N' /FSC/Report/ResearchAndDevelopment/ResultInquest.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (358, N'Lista de Operadores', N' /FSC/Report/FormulationAndAdoption/ReportOperatorList.aspx', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (359, N'Lista de proyectos cerrados', N' /FSC/Report/FormulationAndAdoption/reportClosedProjectsList.aspx ', N'T', 99, 4)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (363, N'Nueva Encuesta', N' /FSC/Execution/addInquest.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (364, N'Nuevo Documento', N' /FSC/ResearchAndDevelopment/addDocuments.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (365, N'Foro del Proyecto', N' /FSC/FormulationAndAdoption/searchForum.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (366, N'Buscar Encuesta', N' /FSC/Execution/searchInquest.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (367, N'Buscar Documento', N' /FSC/ResearchAndDevelopment/searchDocuments.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (368, N'Nuevo Foro', N' /FSC/FormulationAndAdoption/addForum.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (369, N'Diligenciar Encuesta', N' ', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (370, N'Buscar Encuesta Resuelta', N' /FSC/Execution/searchResolvedInquest.aspx', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (371, N'Nuevo Contenido Encuesta', N' /FSC/Execution/addInquestContent.aspx?op=add', N'T', 99, 3)
INSERT [dbo].[Menu] ([Id], [TextField], [URL], [Enabled], [SortOrder], [Level]) VALUES (372, N'Buscar contenido encuesta', N' /FSC/Execution/searchInquestContent.aspx', N'T', 99, 3)
SET IDENTITY_INSERT [dbo].[Menu] OFF
print 'Actualizacion Menus FSC Terminada!'