--CAMBIO DE TAMAÑO DE CAMPOS DE LA TABLA  "TEMPORARYACTIVITIES"

USE FSC_eProject

ALTER table TEMPORARYACTIVITIES ALTER COLUMN COD_PROJECT VARCHAR(MAX) NULL;
ALTER table TEMPORARYACTIVITIES ALTER COLUMN COD_ACTIVITY VARCHAR(MAX) NULL;
ALTER table TEMPORARYACTIVITIES ALTER COLUMN ACTIVITY VARCHAR(MAX) NULL;
ALTER table TEMPORARYACTIVITIES ALTER COLUMN COD_SUBACTIVITY VARCHAR(MAX) NULL;
ALTER table TEMPORARYACTIVITIES ALTER COLUMN SUBACTIVITY VARCHAR(MAX) NULL;
ALTER table TEMPORARYACTIVITIES ALTER COLUMN NIT_ACTORS VARCHAR(MAX) NULL;
ALTER table TEMPORARYACTIVITIES ALTER COLUMN ACTORS VARCHAR(MAX) NULL;
ALTER table TEMPORARYACTIVITIES ALTER COLUMN RESPONSIBLE VARCHAR(MAX) NULL;

