--CAMBIO DE TAMAÑO DE CAMPOS DE LA TABLA  "IDEA" ,"APROBACION IDEA" Y PROYECTO
 

USE FSC_eProject

ALTER table IDEA ALTER COLUMN COST NUMERIC (30,0) NULL;
ALTER table IDEA ALTER COLUMN FSCContribution NUMERIC (30,0) NULL;
ALTER table IDEA ALTER COLUMN CounterpartValue NUMERIC (30,0) NULL;

ALTER table ProjectApprovalRecord ALTER COLUMN ApprovedValue NUMERIC (30,0) NULL;
ALTER table ProjectApprovalRecord ALTER COLUMN aportFSC NUMERIC (30,0) NULL;
ALTER table ProjectApprovalRecord ALTER COLUMN aportOtros NUMERIC (30,0) NULL;

ALTER table PROJECT ALTER COLUMN TOTALCOST NUMERIC (30,0) NULL;
ALTER table PROJECT ALTER COLUMN FSCContribution NUMERIC (30,3) NULL;
ALTER table PROJECT ALTER COLUMN CounterpartValue NUMERIC (30,3) NULL;


