USE [FSC_eProject]
GO

/****** Object:  StoredProcedure [dbo].[VALIDATEIDPROYECTTEMPORATY]    Script Date: 07/28/2013 14:03:48 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VALIDATEIDPROYECTTEMPORATY]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[VALIDATEIDPROYECTTEMPORATY]
GO

